### ISSUE TITLE
Question about accuracy

### ISSUE THREAD

**Issue by Erfanz1999** [YananGu/DVC#4]
I'm very interested in and worship your paper,so i want to reproduce your results. However,i notice that your accuracy is about 2 or 3 percentage higher (acc about GDUMB is lower 3% oppesitely) than the repo of Mai, where you add your own respective achievement on it. I dont understand what changes for that?(I have run Mai's code and get the result in his survey paper). Would you mind to tell me why your codes performence better? I would be very grateful for that.  And should i continue reseach upon your's code or Mai's in your suggestion . Thanks very much!

**Comment by YananGu** [comment]
Thanks for your interest in our work.  In fact, the experiments on the compared methods in our paper are entirely based on Mai's code. We have not modified his code in any way. In my opinion, the performance gap is mainly due to randomness, including the randomness of sample selection or system randomness (so all results are averaged over 15 times). If you're going to do research in this direction, I suggest you run the experiments of all the compared methods.   Just report your own results in your paper. I think it's a fair way to compare.
